# Generated by Django 4.2.5 on 2024-02-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popularuniversity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='PopularUniversity',
        ),
    ]
