# Generated by Django 4.2.5 on 2024-02-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_popularfaculties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='PopularFaculties',
        ),
        migrations.DeleteModel(
            name='PopularUniversity',
        ),
    ]
