# Generated by Django 4.2.5 on 2024-02-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_aboutus_delete_popularfaculties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('number', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
