# Generated by Django 4.2.5 on 2024-02-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_popularfaculties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popularuniversity',
            old_name='students',
            new_name='student',
        ),
        migrations.AddField(
            model_name='popularfaculties',
            name='student',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
