# Generated by Django 4.2.5 on 2024-02-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopularUniversity',
            new_name='University',
        ),
    ]
