# Generated by Django 4.2.5 on 2024-02-27 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_popularuniversity_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.DeleteModel(
            name='PopularFaculties',
        ),
        migrations.DeleteModel(
            name='University',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
