# Generated by Django 4.2.5 on 2024-02-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_aboutus_popularfaculties_university_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='popularfaculties',
            old_name='student',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='university',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
