# Generated by Django 4.2.5 on 2024-02-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_rename_popularfaculties_faculties_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Прием документов'), (2, 'прием закрыт')])),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='faculties',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.faculties'),
            preserve_default=False,
        ),
    ]
