# Generated by Django 4.2.5 on 2024-02-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_p_university_personal_faculties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p_university',
            name='date',
            field=models.DateField(),
        ),
    ]
