# Generated by Django 4.2.5 on 2024-02-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_p_university_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('waiting', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='p_university',
            name='single',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.single'),
            preserve_default=False,
        ),
    ]
