# Generated by Django 4.2.5 on 2024-02-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_assistent_single_p_university_single'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Assistent',
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='p_university',
            name='single',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='faculties',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='students',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='university',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.DeleteModel(
            name='Faculties',
        ),
        migrations.DeleteModel(
            name='P_University',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.DeleteModel(
            name='Single',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
