# Generated by Django 4.2.5 on 2024-02-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_aboutus_assistent_contactus_faculties_single_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistent',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistent',
            name='phone',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
