# Generated by Django 4.2.5 on 2024-02-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_assistent_email_assistent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='U_Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('yearfoundation', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('matto', models.CharField(max_length=100)),
                ('bachelors', models.IntegerField()),
                ('masters', models.IntegerField()),
                ('teachers', models.IntegerField()),
                ('startingsalary', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
