# Generated by Django 4.2.5 on 2024-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_university_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='u_cabinet',
            name='yearfoundation',
            field=models.IntegerField(),
        ),
    ]
